require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'FtMobileAgentExample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

      pod 'FTMobileReactNativeSDK', :path => '../..'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!({ 'Flipper-Folly' => '2.3.0' })
#  pod 'react-native-config', :path => '../node_modules/react-native-config'

  post_install do |installer|
    # react-native版本小于0.69.9时使用，修复xcode14.3出现的问题
    find_and_replace("../node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp",
      "node->getLayout().hadOverflow() |\n","node->getLayout().hadOverflow() ||\n")
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
      end
    end
  end
end

def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
      text = File.read(name)
      replace = text.gsub(findstr,replacestr)
      if text != replace
          puts "Fix: " + name
          File.open(name, "w") { |file| file.puts replace }
          STDOUT.flush
      end
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end
